# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 17:18
from __future__ import unicode_literals

from django.db import migrations
import ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0022_auto_20180525_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='address',
            field=ipam.fields.IPAddressField(help_text='IPv4 or IPv6 address (with mask)', unique=True),
        ),
    ]
