# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0056_auto_20180519_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Management'), (2, 'Host OS')], default=1),
            preserve_default=False,
        ),
    ]
