# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 19:36
from __future__ import unicode_literals

from django.db import migrations
import utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0057_interface_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=utilities.fields.NullableCharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('rack', 'position', 'face'), ('virtual_chassis', 'vc_position'), ('rack', 'name')]),
        ),
    ]
