# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0058_auto_20180521_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Management'), (2, 'Host OS'), (3, 'Switch port')]),
        ),
    ]
