# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0059_auto_20180523_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='is_openflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interface',
            name='state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
