# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0060_auto_20180523_0318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('device', 'name', 'mac_address')]),
        ),
    ]
