# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0004_virtualmachine_add_role'),
        ('dcim', '0061_auto_20180523_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Management'), (2, 'Host OS'), (3, 'Switch port'), (4, 'Virtual bridge')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('virtual_machine', 'name'), ('device', 'name')]),
        ),
    ]
