# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 02:05
from __future__ import unicode_literals

import dcim.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0062_auto_20180524_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='mac_address',
            field=dcim.fields.MACAddressField(blank=True, null=True, unique=True, verbose_name='MAC Address'),
        ),
    ]
