# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 15:57
from __future__ import unicode_literals

import dcim.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0066_auto_20180525_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceMacTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', dcim.fields.MACAddressField(blank=True, null=True, verbose_name='MAC Address')),
            ],
        ),
        migrations.AlterModelOptions(
            name='interface',
            options={'ordering': ['device', 'virtual_machine', 'name']},
        ),
        migrations.AddField(
            model_name='interfacemactraffic',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffics', to='dcim.Interface'),
        ),
    ]
