# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0067_auto_20180529_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacemactraffic',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffics', to='dcim.Interface'),
        ),
    ]
