# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0068_auto_20180529_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfacemactraffic',
            name='interface',
        ),
        migrations.DeleteModel(
            name='InterfaceMacTraffic',
        ),
    ]
