# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 16:08
from __future__ import unicode_literals

import dcim.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0069_auto_20180529_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceMacTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', dcim.fields.MACAddressField(blank=True, null=True, verbose_name='MAC Address')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffics', to='dcim.Interface')),
            ],
        ),
    ]
