# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0070_interfacemactraffic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interfacemactraffic',
            unique_together=set([('interface', 'mac_address')]),
        ),
    ]
