# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0071_auto_20180529_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[[1, 'Active'], [0, 'Offline'], [2, 'Planned'], [3, 'Staged'], [4, 'Failed'], [5, 'Inventory'], [6, 'Powered off']], default=1, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([]),
        ),
    ]
