# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0072_auto_20180605_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicebay',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_bays', to='dcim.Device', verbose_name='parent device'),
        ),
        migrations.AlterField(
            model_name='devicebay',
            name='installed_device',
            field=models.OneToOneField(blank=True, help_text='Bay device installed inside a parent device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_bay', to='dcim.Device', verbose_name='bay device'),
        ),
        migrations.AlterField(
            model_name='interfaceconnection',
            name='interface_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_as_a', to='dcim.Interface'),
        ),
        migrations.AlterField(
            model_name='interfaceconnection',
            name='interface_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_as_b', to='dcim.Interface'),
        ),
    ]
