# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0074_auto_20180614_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interface',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
