# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0075_auto_20180623_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='is_openflow',
            new_name='is_trunk',
        ),
        migrations.AddField(
            model_name='interface',
            name='allowed_vlans',
            field=models.TextField(blank=True, help_text='Comma delimitered list, eg. 100-109,200-209,700-799.', null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='untagged_vlan',
            field=models.ForeignKey(blank=True, help_text='Untagged VLAN is also known as native VLAN', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces_as_untagged', to='ipam.VLAN', verbose_name='Untagged VLAN'),
        ),
    ]
