# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0076_auto_20180624_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
