# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0077_auto_20180712_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='dcim.DeviceType'),
        ),
    ]
