# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0078_inventoryitem_device_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('rack', 'position', 'face'), ('virtual_chassis', 'vc_position')]),
        ),
    ]
