# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_unicode_literals'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
