# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0005_secret_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='dcim.Interface'),
        ),
    ]
