# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0004_virtualmachine_add_role'),
        ('secrets', '0006_auto_20180523_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='virtualization.VirtualMachine'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='dcim.Device'),
        ),
    ]
