# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0007_auto_20180524_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secrets', to='dcim.Interface'),
        ),
    ]
